Zoozoo-Club/Back-End

src/main/java/Zoozoo/ZoozooClub/company/entity/Company.java, src/main/java/Zoozoo/ZoozooClub/user/entity/User.java
=> fix: Entity 삭제된 사항들 수정

.gitignore, gradlew, gradlew.bat, src/main/java/Zoozoo/ZoozooClub/commons/kis/KoreaInvestmentApiService.java, src/main/java/Zoozoo/ZoozooClub/commons/kis/StockController.java, src/main/java/Zoozoo/ZoozooClub/commons/kis/dto/ApiResponseDTO.java, src/main/java/Zoozoo/ZoozooClub/commons/kis/dto/BalanceResponseDTO.java, src/main/java/Zoozoo/ZoozooClub/commons/kis/dto/StockPriceOutput.java, src/main/java/Zoozoo/ZoozooClub/commons/kis/dto/StockPriceResponseDTO.java
ex)  (제목 작성후 지워주세요!)
> 
- OPEN API 받아오는 코드
- ENV 파일에 키값 및,계좌 정보
=> [Feat] KIS 현재가 및 잔고 조회

src/main/java/Zoozoo/ZoozooClub/commons/kis/dto/BalanceResponseDTO.java
[Feat] BalanceResponseDTO에 변수 추가
=> feat: 변수, 주석 추가

src/main/java/Zoozoo/ZoozooClub/account/entity/Account.java, src/main/java/Zoozoo/ZoozooClub/account/service/AccountService.java, src/main/java/Zoozoo/ZoozooClub/commons/kis/KoreaInvestmentApiService.java, src/main/java/Zoozoo/ZoozooClub/commons/kis/StockController.java, src/main/java/Zoozoo/ZoozooClub/commons/kis/dto/BalanceResponseDTO.java
=> feat: dto 수정, getStocckBalance 파라미터 수정

src/main/java/Zoozoo/ZoozooClub/club/controller/ClubController.java, src/main/java/Zoozoo/ZoozooClub/club/dto/ClubResponseDto.java, src/main/java/Zoozoo/ZoozooClub/club/exception/NoClubException.java, src/main/java/Zoozoo/ZoozooClub/club/repository/ClubRepository.java, src/main/java/Zoozoo/ZoozooClub/club/service/ClubService.java, src/main/java/Zoozoo/ZoozooClub/commons/auth/LoginInterceptor.java, src/main/java/Zoozoo/ZoozooClub/company/entity/Company.java, src/main/java/Zoozoo/ZoozooClub/company/exception/NoStockException.java, src/main/java/Zoozoo/ZoozooClub/company/repository/CompanyRepository.java, src/main/java/Zoozoo/ZoozooClub/company/service/CompanyService.java, src/main/java/Zoozoo/ZoozooClub/stock/entity/Stock.java
- redis에 club 및 account 정보가 들어오면 Club Portfolio 구현하면 될듯
- Redis 구축되고 나서 account 정보를 통해 클럽 포트폴리오 구축하는 로직을 추가해야 될듯
- close #00
=> feat: files - 클럽 기업 상세 페이지 구현중

src/main/java/Zoozoo/ZoozooClub/user/dto/AuthLoginResponseDto.java, src/main/java/Zoozoo/ZoozooClub/user/service/AuthService.java
=> refactor: 프론트 요청에 따른 로그인 응답 Dto 변경

.github/workflows/CD.yml, build.gradle, src/main/java/Zoozoo/ZoozooClub/ZoozooClubApplication.java, src/main/java/Zoozoo/ZoozooClub/account/controller/AccountController.java, src/main/java/Zoozoo/ZoozooClub/account/service/AccountService.java, src/main/java/Zoozoo/ZoozooClub/commons/kis/dto/BalanceResponseDTO.java, src/main/java/Zoozoo/ZoozooClub/commons/redis/RedisBalanceService.java, src/main/java/Zoozoo/ZoozooClub/config/RedisConfig.java, src/main/java/Zoozoo/ZoozooClub/ranking/service/BalanceUpdateService.java
=> [Feat] 계좌기준으로 잔고 업데이트 

src/main/java/Zoozoo/ZoozooClub/account/service/AccountService.java, src/main/java/Zoozoo/ZoozooClub/commons/kis/StockController.java, src/main/java/Zoozoo/ZoozooClub/user/entity/User.java, src/main/java/Zoozoo/ZoozooClub/user/service/AuthService.java
=> FIX : JWT의 유저의 보유 자산 조회하도록 변경

src/main/java/Zoozoo/ZoozooClub/commons/kis/KoreaInvestmentApiService.java, src/main/java/Zoozoo/ZoozooClub/commons/kis/StockController.java, src/main/java/Zoozoo/ZoozooClub/commons/kis/dto/OrderRequestDTO.java, src/main/java/Zoozoo/ZoozooClub/commons/kis/dto/OrderResponseDTO.java
=> feat: 매수 매도 api

src/main/java/Zoozoo/ZoozooClub/commons/kis/StockController.java
=> feat: 매수 매도 토큰에서 유저 아이디로 받아서 진행하도록 수정

src/main/java/Zoozoo/ZoozooClub/follow/controller/FollowerController.java, src/main/java/Zoozoo/ZoozooClub/follow/dto/FollowResponseDTO.java, src/main/java/Zoozoo/ZoozooClub/follow/entity/Follower.java, src/main/java/Zoozoo/ZoozooClub/follow/repository/FollowerRepository.java, src/main/java/Zoozoo/ZoozooClub/follow/service/FollowerService.java
- 팔로우
- 팔로잉
- 팔로워
- 언팔로우
- 특정사용자의팔로워현황
- 특정사용자의팔로잉현황
- 팔로우상태확인
=> feat: 팔로우 CRUD 구현

src/main/java/Zoozoo/ZoozooClub/follow/controller/FollowerController.java
=> feat: uri 수정

src/main/java/Zoozoo/ZoozooClub/balance/exception/NotFoundBalanceException.java, src/main/java/Zoozoo/ZoozooClub/balance/service/BalanceService.java, src/main/java/Zoozoo/ZoozooClub/product/controller/ProductController.java, src/main/java/Zoozoo/ZoozooClub/product/dto/ProductDto.java, src/main/java/Zoozoo/ZoozooClub/product/entity/Product.java, src/main/java/Zoozoo/ZoozooClub/product/exception/NotFoundProductsException.java, src/main/java/Zoozoo/ZoozooClub/product/repository/ProductRepository.java, src/main/java/Zoozoo/ZoozooClub/product/service/ProductService.java, src/main/java/Zoozoo/ZoozooClub/ranking/service/RankingService.java, src/main/java/Zoozoo/ZoozooClub/user/exception/NotFoundAccountException.java, src/main/java/Zoozoo/ZoozooClub/user/repository/UserRepository.java
=>  [Feat] 상품조회

src/main/java/Zoozoo/ZoozooClub/user/service/AuthService.java
=> [Feat]  getAccountById 아이디로 계좌조회하는 API작성

src/main/java/Zoozoo/ZoozooClub/post/controller/PostController.java, src/main/java/Zoozoo/ZoozooClub/post/dto/PostResponseDTO.java, src/main/java/Zoozoo/ZoozooClub/post/entity/AllPost.java, src/main/java/Zoozoo/ZoozooClub/post/entity/Post.java, src/main/java/Zoozoo/ZoozooClub/post/repository/AllPostRepository.java, src/main/java/Zoozoo/ZoozooClub/post/repository/PostRepository.java, src/main/java/Zoozoo/ZoozooClub/post/service/PostService.java
=> feat: 게시글 조회 api

src/main/java/Zoozoo/ZoozooClub/balance/service/BalanceService.java, src/main/java/Zoozoo/ZoozooClub/club/service/ClubService.java, src/main/java/Zoozoo/ZoozooClub/commons/kis/StockController.java, src/main/java/Zoozoo/ZoozooClub/company/entity/Company.java, src/main/java/Zoozoo/ZoozooClub/ranking/controller/RankingController.java, src/main/java/Zoozoo/ZoozooClub/ranking/dto/InClubDto.java, src/main/java/Zoozoo/ZoozooClub/ranking/dto/RankingDto.java, src/main/java/Zoozoo/ZoozooClub/ranking/entity/InClubRanking.java, src/main/java/Zoozoo/ZoozooClub/ranking/entity/Ranking.java, src/main/java/Zoozoo/ZoozooClub/ranking/service/RankingService.java, src/main/java/Zoozoo/ZoozooClub/user/controller/UserController.java, src/main/java/Zoozoo/ZoozooClub/user/service/AuthService.java
=> feat: 랭킹 서비스 개발 완료

src/main/java/Zoozoo/ZoozooClub/TestController.java, src/main/java/Zoozoo/ZoozooClub/club/controller/ClubController.java, src/main/java/Zoozoo/ZoozooClub/club/repository/ClubRepository.java, src/main/java/Zoozoo/ZoozooClub/club/service/ClubService.java, src/main/java/Zoozoo/ZoozooClub/commons/kis/StockController.java, src/main/java/Zoozoo/ZoozooClub/follow/controller/FollowerController.java, src/main/java/Zoozoo/ZoozooClub/post/controller/PostController.java, src/main/java/Zoozoo/ZoozooClub/stock/repository/StockRepository.java, src/main/java/Zoozoo/ZoozooClub/stock/service/StockService.java
=> [Feat] 클럽기준 현재가 가져오기 및 누락된 어노테이션 추가

src/main/java/Zoozoo/ZoozooClub/club/controller/ClubController.java, src/main/java/Zoozoo/ZoozooClub/club/service/ClubService.java, src/main/java/Zoozoo/ZoozooClub/commons/kis/KoreaInvestmentApiService.java, src/main/java/Zoozoo/ZoozooClub/commons/kis/StockController.java, src/main/java/Zoozoo/ZoozooClub/follow/entity/Follower.java
=> 클럽 아이디로 현재가 받아오기

src/main/java/Zoozoo/ZoozooClub/club/dto/ClubResponseDto.java, src/main/java/Zoozoo/ZoozooClub/club/entity/Club.java, src/main/java/Zoozoo/ZoozooClub/club/service/ClubService.java, src/main/java/Zoozoo/ZoozooClub/commons/kis/StockController.java, src/main/java/Zoozoo/ZoozooClub/commons/kis/dto/MyStockBalanceDto.java, src/main/java/Zoozoo/ZoozooClub/commons/kis/dto/OtherStockBalanceDto.java, src/main/java/Zoozoo/ZoozooClub/company/entity/Company.java, src/main/java/Zoozoo/ZoozooClub/product/service/ProductService.java, src/main/java/Zoozoo/ZoozooClub/ranking/controller/RankingController.java, src/main/java/Zoozoo/ZoozooClub/ranking/dto/RankingDto.java, src/main/java/Zoozoo/ZoozooClub/user/entity/User.java, src/main/java/Zoozoo/ZoozooClub/user/service/AuthService.java
=> feat : files - 여러 기능들 추가

src/main/java/Zoozoo/ZoozooClub/club/service/ClubService.java, src/main/java/Zoozoo/ZoozooClub/commons/kis/StockController.java, src/main/java/Zoozoo/ZoozooClub/commons/kis/dto/StockPriceResponseDTO.java, src/main/java/Zoozoo/ZoozooClub/stock/repository/StockRepository.java
=> [Feat] 현재가 조회시 종목명 함께 보내주기
